/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.production.jsonc --env-file=.env.example --include-runtime=false --strict-vars=false cloudflare-env.d.ts` (hash: b5ee1a06e59cfcbc2d092edcdbb5fe42)
interface __BaseEnv_Env {
	MEDIA: R2Bucket;
	DB: D1Database;
	VIEW_RATE_LIMITER: RateLimit;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	APP_ENV: string;
	INSTANCE_ID: string;
	DB_SCHEMA_MODE: string;
	CSP_MODE: string;
	REGISTRATION_ENABLED: string;
	PUBLIC_SITE_URL: string;
	EMAIL_FROM: string;
	ADMIN_PASSWORD: string;
	ADMIN_SESSION_SECRET: string;
	MCP_WRITE_TOKEN: string;
	VIEWS_IDENTITY_SECRET: string;
	ADMIN_EMAILS: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/server/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "INSTANCE_ID" | "DB_SCHEMA_MODE" | "CSP_MODE" | "REGISTRATION_ENABLED" | "PUBLIC_SITE_URL" | "EMAIL_FROM" | "ADMIN_PASSWORD" | "ADMIN_SESSION_SECRET" | "MCP_WRITE_TOKEN" | "VIEWS_IDENTITY_SECRET" | "ADMIN_EMAILS">> {}
}
