export function mermaidAppearance(dark: boolean) {
  return {
    theme: "base" as const,
    fontFamily: '"PingFang SC", "Microsoft YaHei UI", "Microsoft YaHei", system-ui, sans-serif',
    fontSize: 15,
    htmlLabels: false,
    flowchart: {
      useMaxWidth: false,
      wrappingWidth: 220,
      nodeSpacing: 40,
      rankSpacing: 54,
      padding: 18,
    },
    themeVariables: dark ? {
      darkMode: true,
      background: "#111216",
      primaryColor: "#22252c",
      primaryBorderColor: "#48505d",
      primaryTextColor: "#f2f3f6",
      secondaryColor: "#1b2b3b",
      secondaryBorderColor: "#37618a",
      secondaryTextColor: "#e7f1fc",
      tertiaryColor: "#171a20",
      tertiaryBorderColor: "#343b46",
      tertiaryTextColor: "#dce0e7",
      clusterBkg: "#171a20",
      clusterBorder: "#343b46",
      lineColor: "#808a99",
      textColor: "#e7e9ee",
      nodeBorder: "#48505d",
      nodeTextColor: "#f2f3f6",
      edgeLabelBackground: "#111216",
    } : {
      darkMode: false,
      background: "#ffffff",
      primaryColor: "#f8f9fb",
      primaryBorderColor: "#cbd3de",
      primaryTextColor: "#252a32",
      secondaryColor: "#eaf3fc",
      secondaryBorderColor: "#a9c9e9",
      secondaryTextColor: "#243e5d",
      tertiaryColor: "#f7f8fa",
      tertiaryBorderColor: "#dce1e8",
      tertiaryTextColor: "#4c5664",
      clusterBkg: "#f7f8fa",
      clusterBorder: "#dce1e8",
      lineColor: "#8592a1",
      textColor: "#333a44",
      nodeBorder: "#cbd3de",
      nodeTextColor: "#252a32",
      edgeLabelBackground: "#ffffff",
    },
  };
}
