/** Local bootstrap only; production runs SQL migration 0021 and verifies schema 23. */
export const ORGANIZATION_DDL = [
  "CREATE TABLE IF NOT EXISTS organizations (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, slug TEXT NOT NULL, name TEXT NOT NULL, owner_user_id INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','archived')), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);",
  "CREATE TABLE IF NOT EXISTS organization_memberships (organization_id INTEGER NOT NULL, user_id INTEGER NOT NULL, role TEXT NOT NULL CHECK(role IN ('owner','admin','member')), status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','suspended')), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (organization_id,user_id));",
  "CREATE TABLE IF NOT EXISTS organization_invitations (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, organization_id INTEGER NOT NULL, email TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('admin','member')), token_hash TEXT NOT NULL, invited_by INTEGER NOT NULL, expires_at INTEGER NOT NULL, accepted_by INTEGER, accepted_at INTEGER, revoked_at INTEGER, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);",
  "CREATE TABLE IF NOT EXISTS organization_units (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, organization_id INTEGER NOT NULL, parent_id INTEGER, name TEXT NOT NULL, sort_order INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);",
  "CREATE TABLE IF NOT EXISTS organization_unit_memberships (organization_id INTEGER NOT NULL, unit_id INTEGER NOT NULL, user_id INTEGER NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(organization_id,unit_id,user_id));",
  "CREATE UNIQUE INDEX IF NOT EXISTS organizations_slug_uidx ON organizations(slug);",
  "CREATE INDEX IF NOT EXISTS organization_memberships_user_idx ON organization_memberships(user_id,organization_id);",
  "CREATE UNIQUE INDEX IF NOT EXISTS organization_invitations_token_uidx ON organization_invitations(token_hash);",
  "CREATE UNIQUE INDEX IF NOT EXISTS organization_invitations_pending_uidx ON organization_invitations(organization_id,email) WHERE accepted_at IS NULL AND revoked_at IS NULL;",
  "CREATE INDEX IF NOT EXISTS organization_invitations_org_idx ON organization_invitations(organization_id,created_at);",
  "CREATE UNIQUE INDEX IF NOT EXISTS organization_units_sibling_uidx ON organization_units(organization_id,parent_id,name);",
  "CREATE UNIQUE INDEX IF NOT EXISTS organization_units_root_uidx ON organization_units(organization_id,name) WHERE parent_id IS NULL;",
  "CREATE INDEX IF NOT EXISTS organization_units_tree_idx ON organization_units(organization_id,parent_id,sort_order,id);",
  "CREATE INDEX IF NOT EXISTS organization_unit_memberships_user_idx ON organization_unit_memberships(user_id,organization_id);"
];
export const ORGANIZATION_GUARDS = [
  "CREATE TRIGGER IF NOT EXISTS org_membership_insert_guard BEFORE INSERT ON organization_memberships\nWHEN NOT EXISTS(SELECT 1 FROM organizations o WHERE o.id=NEW.organization_id AND o.status='active')\nOR NOT EXISTS(SELECT 1 FROM users u WHERE u.id=NEW.user_id AND u.status='active')\nOR EXISTS(SELECT 1 FROM organizations o WHERE o.id=NEW.organization_id AND\n ((o.owner_user_id=NEW.user_id AND (NEW.role<>'owner' OR NEW.status<>'active'))\n OR (o.owner_user_id<>NEW.user_id AND NEW.role='owner')))\nBEGIN SELECT RAISE(ABORT,'organization member boundary'); END;",
  "CREATE TRIGGER IF NOT EXISTS org_membership_update_guard BEFORE UPDATE ON organization_memberships\nWHEN NEW.organization_id<>OLD.organization_id OR NEW.user_id<>OLD.user_id\nOR NOT EXISTS(SELECT 1 FROM organizations o WHERE o.id=NEW.organization_id AND o.status='active')\nOR EXISTS(SELECT 1 FROM organizations o WHERE o.id=NEW.organization_id AND\n ((o.owner_user_id=NEW.user_id AND (NEW.role<>'owner' OR NEW.status<>'active'))\n OR (o.owner_user_id<>NEW.user_id AND NEW.role='owner')))\nBEGIN SELECT RAISE(ABORT,'organization member boundary'); END;",
  "CREATE TRIGGER IF NOT EXISTS org_owner_membership_delete_guard BEFORE DELETE ON organization_memberships\nWHEN EXISTS(SELECT 1 FROM organizations o WHERE o.id=OLD.organization_id AND o.owner_user_id=OLD.user_id)\nBEGIN SELECT RAISE(ABORT,'cannot remove organization owner'); END;",
  "CREATE TRIGGER IF NOT EXISTS org_member_units_cleanup AFTER DELETE ON organization_memberships\nBEGIN DELETE FROM organization_unit_memberships WHERE organization_id=OLD.organization_id AND user_id=OLD.user_id; END;",
  "CREATE TRIGGER IF NOT EXISTS org_unit_insert_guard BEFORE INSERT ON organization_units\nWHEN NOT EXISTS(SELECT 1 FROM organizations o WHERE o.id=NEW.organization_id AND o.status='active')\nOR (NEW.parent_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM organization_units p\n WHERE p.id=NEW.parent_id AND p.organization_id=NEW.organization_id))\nBEGIN SELECT RAISE(ABORT,'organization unit parent boundary'); END;",
  "CREATE TRIGGER IF NOT EXISTS org_unit_update_guard BEFORE UPDATE ON organization_units\nWHEN NEW.organization_id<>OLD.organization_id\nOR (NEW.parent_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM organization_units p\n WHERE p.id=NEW.parent_id AND p.organization_id=NEW.organization_id))\nOR (NEW.parent_id IS NOT NULL AND EXISTS(\n WITH RECURSIVE ancestors(id,parent_id) AS (\n  SELECT id,parent_id FROM organization_units WHERE id=NEW.parent_id AND organization_id=NEW.organization_id\n  UNION ALL\n  SELECT p.id,p.parent_id FROM organization_units p JOIN ancestors a ON p.id=a.parent_id WHERE p.organization_id=NEW.organization_id\n ) SELECT 1 FROM ancestors WHERE id=OLD.id\n))\nBEGIN SELECT RAISE(ABORT,'organization unit cycle or cross-organization parent'); END;",
  "CREATE TRIGGER IF NOT EXISTS org_unit_delete_guard BEFORE DELETE ON organization_units\nWHEN EXISTS(SELECT 1 FROM organization_units c WHERE c.parent_id=OLD.id)\nOR EXISTS(SELECT 1 FROM organization_unit_memberships m WHERE m.organization_id=OLD.organization_id AND m.unit_id=OLD.id)\nBEGIN SELECT RAISE(ABORT,'organization unit is not empty'); END;",
  "CREATE TRIGGER IF NOT EXISTS org_unit_member_insert_guard BEFORE INSERT ON organization_unit_memberships\nWHEN NOT EXISTS(SELECT 1 FROM organization_units d WHERE d.id=NEW.unit_id AND d.organization_id=NEW.organization_id)\nOR NOT EXISTS(SELECT 1 FROM organization_memberships m JOIN organizations o ON o.id=m.organization_id JOIN users u ON u.id=m.user_id\n WHERE m.organization_id=NEW.organization_id AND m.user_id=NEW.user_id AND m.status='active' AND o.status='active' AND u.status='active')\nBEGIN SELECT RAISE(ABORT,'department membership boundary'); END;",
  "CREATE TRIGGER IF NOT EXISTS org_unit_member_update_guard BEFORE UPDATE ON organization_unit_memberships\nWHEN NEW.organization_id<>OLD.organization_id OR NEW.unit_id<>OLD.unit_id OR NEW.user_id<>OLD.user_id\nBEGIN SELECT RAISE(ABORT,'department membership immutable'); END;"
];
