/** Fail closed on cross-tenant references; tolerate orphaned historical rows only in owner workspace 1. */
export const WORKSPACE_GUARD_TRIGGERS = [
  "CREATE TRIGGER IF NOT EXISTS posts_workspace_insert_guard BEFORE INSERT ON posts\nWHEN (NEW.workspace_id <> 1 AND (\n  NEW.space_id IS NULL\n  OR NOT EXISTS(SELECT 1 FROM categories c WHERE c.id=NEW.category_id AND c.workspace_id=NEW.workspace_id)\n  OR NOT EXISTS(SELECT 1 FROM spaces s WHERE s.id=NEW.space_id AND s.workspace_id=NEW.workspace_id)\n))\nOR EXISTS(SELECT 1 FROM categories c WHERE c.id=NEW.category_id AND c.workspace_id<>NEW.workspace_id)\nOR (NEW.space_id IS NOT NULL AND EXISTS(SELECT 1 FROM spaces s WHERE s.id=NEW.space_id AND s.workspace_id<>NEW.workspace_id))\nBEGIN SELECT RAISE(ABORT,'posts workspace boundary'); END;",
  "CREATE TRIGGER IF NOT EXISTS posts_workspace_update_guard BEFORE UPDATE OF workspace_id,space_id,category_id ON posts\nWHEN (NEW.workspace_id <> 1 AND (\n  NEW.space_id IS NULL\n  OR NOT EXISTS(SELECT 1 FROM categories c WHERE c.id=NEW.category_id AND c.workspace_id=NEW.workspace_id)\n  OR NOT EXISTS(SELECT 1 FROM spaces s WHERE s.id=NEW.space_id AND s.workspace_id=NEW.workspace_id)\n))\nOR EXISTS(SELECT 1 FROM categories c WHERE c.id=NEW.category_id AND c.workspace_id<>NEW.workspace_id)\nOR (NEW.space_id IS NOT NULL AND EXISTS(SELECT 1 FROM spaces s WHERE s.id=NEW.space_id AND s.workspace_id<>NEW.workspace_id))\nBEGIN SELECT RAISE(ABORT,'posts workspace boundary'); END;",
  "CREATE TRIGGER IF NOT EXISTS spaces_workspace_insert_guard BEFORE INSERT ON spaces\nWHEN (NEW.workspace_id <> 1 AND NOT EXISTS(SELECT 1 FROM workspaces w WHERE w.id=NEW.workspace_id))\n OR (NEW.workspace_id <> 1 AND NEW.parent_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM spaces s WHERE s.id=NEW.parent_id AND s.workspace_id=NEW.workspace_id))\n OR (NEW.parent_id IS NOT NULL AND EXISTS(SELECT 1 FROM spaces s WHERE s.id=NEW.parent_id AND s.workspace_id<>NEW.workspace_id))\nBEGIN SELECT RAISE(ABORT,'spaces workspace boundary'); END;",
  "CREATE TRIGGER IF NOT EXISTS spaces_workspace_update_guard BEFORE UPDATE OF workspace_id,parent_id ON spaces\nWHEN (NEW.workspace_id <> 1 AND NOT EXISTS(SELECT 1 FROM workspaces w WHERE w.id=NEW.workspace_id))\n OR (NEW.workspace_id <> 1 AND NEW.parent_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM spaces s WHERE s.id=NEW.parent_id AND s.workspace_id=NEW.workspace_id))\n OR (NEW.parent_id IS NOT NULL AND EXISTS(SELECT 1 FROM spaces s WHERE s.id=NEW.parent_id AND s.workspace_id<>NEW.workspace_id))\nBEGIN SELECT RAISE(ABORT,'spaces workspace boundary'); END;",
  "CREATE TRIGGER IF NOT EXISTS attachments_workspace_insert_guard BEFORE INSERT ON attachments\nWHEN (NEW.workspace_id <> 1 AND NOT EXISTS(SELECT 1 FROM workspaces w WHERE w.id=NEW.workspace_id))\n OR (NEW.workspace_id <> 1 AND NEW.post_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM posts p WHERE p.id=NEW.post_id AND p.workspace_id=NEW.workspace_id))\n OR (NEW.post_id IS NOT NULL AND EXISTS(SELECT 1 FROM posts p WHERE p.id=NEW.post_id AND p.workspace_id<>NEW.workspace_id))\nBEGIN SELECT RAISE(ABORT,'attachments workspace boundary'); END;",
  "CREATE TRIGGER IF NOT EXISTS attachments_workspace_update_guard BEFORE UPDATE OF workspace_id,post_id ON attachments\nWHEN (NEW.workspace_id <> 1 AND NOT EXISTS(SELECT 1 FROM workspaces w WHERE w.id=NEW.workspace_id))\n OR (NEW.workspace_id <> 1 AND NEW.post_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM posts p WHERE p.id=NEW.post_id AND p.workspace_id=NEW.workspace_id))\n OR (NEW.post_id IS NOT NULL AND EXISTS(SELECT 1 FROM posts p WHERE p.id=NEW.post_id AND p.workspace_id<>NEW.workspace_id))\nBEGIN SELECT RAISE(ABORT,'attachments workspace boundary'); END;",
];
